/*                               ASSIGNMENT 1

Topic - Input and Output Function
Description - Cover page of magazine
Date Of Submission -03/07/2018 */
#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
cout<<"\n\n\n\n\n\n\n\n\n\t\t\t   \" \aTHE NEXT DECADE\a \"";
cout<<"\n\n\t\t\t\t\t\t-SCIENCE";
cout<<"\t\t\t\t\t\t\t\t\t\t-TECH";
cout<<"\n\n------------------------------------------------------------------------------";
cout<<"\n\n\t\t\t   *-2018  TO  2019-*";
cout<<"\n\n\n\n\t\t*3 D PRINT HUMAN ORGAN";
cout<<"\n\n\t\t*FIRST INDIAN MANNED SPACE PROGRAMME";
cout<<"\n\n\t\t*GOOGLE SPEEDS UP INTERNET";
cout<<"\n\n\n\n\t\tVISIT \: http\:\\\\www.DIG\_IT.XI C";
cout<<"\n\t\t\t\t\t\t-*SIGNED BY";
cout<<"\t\t\t\t\t\t\t\t\t\a\a ABHIJITH MALLYA"; getch();
}





          













